### ISSUE TITLE
Issue with correct consumer/source configuration for production

### ISSUE THREAD

**Issue by msg4ashish** [sksamuel/pulsar4s#212]
Hi,

I have a simple service (Record ingester service) where I need to consume messages present on apache pulsar to 
elastic store and for that I am using com.sksamuel.pulsar4s.akka.

Messages on pulsar is produced by another service which is Record pump service.
Both these services are to be deployed separately, in production.

Here is my source:
  	
  	`private val source = committableSource(consumerFn)`

This code works fine and its able to consume message from pulsar and write to ES.
However, I am not sure if we should be using MessageId.earliest when creating source

`private val source = committableSource(consumerFn, Some(MessageId.earliest))`

While testing, I found pros and cons of both that is without using MessageId.earliest
and with using MessageId.earliest, but none of them are suitable for production (as per my opinion).

1. Without using MessageId.earliest:
 
 a. This adds a constraint that this Record ingester service has to be up before
 we put start Record pump service. 
 
 b. If my record ingester service goes down (due to an issue or due to maintenance), the messages
 produced on pulsar by record pump service will not get consumed after the ingester service is back up.
 These messages are lost and never gets consumed.
 
 So, I think the logic is that only those messages will be consumed which will be put on pulsar
 AFTER the consumer has subscribed to that topic.
 
 But, I don't think its acceptable in production for the reason mentioned in point a and point b.
 

2. With MessageId.earliest:
a. When we use this, any time my record ingester service comes back up (after downtime or maintenance),
it starts consuming all message since the very beginning.
I have the logic that records with same id gets overwritten at ES side, so it really doesn't do any harm
but still I don't think this is the thing - as there would be millions of messages on that topic
and it will first consume the ones that are already consumed (which is a waste).

This also to me is unacceptable in production.

Can anyone please help me out in what configuration to use which solves both cases.
I tried various configurations such as using  subscriptionInitialPosition = Some(SubscriptionInitialPosition.Earliest)
but no luck.

Complete code:

  ```
//consumer
  private val consumerFn = () =>
    pulsarClient.consumer(
      ConsumerConfig(
        subscriptionName = Subscription.generate,
        topics = Seq(statementTopic),
        subscriptionType = Some(SubscriptionType.Shared)
      )
    )
    
    //create source
	private val source = committableSource(consumerFn)
	
	
	//create intermediate flow
	private val intermediateFlow = Flow[CommittableMessage[Array[Byte]]].map {
    committableSourceMessage =>
      val message                     = committableSourceMessage.message
      val obj: MyObject = MyObject.parseFrom(message.value)
      WriteMessage.createIndexMessage(obj.id, JsonUtil.toJson(obj))
  }.via(
    ElasticsearchFlow.create(
      indexName = "myindex",
      typeName = "_doc",
      settings = ElasticsearchWriteSettings.Default,
      StringMessageWriter
    )
  )
	
	source.via(intermediateFlow).run()
```

Thanks

**Comment by gmethvin** [comment]
@msg4ashish I don't believe your problem is with this library, and this tracker is really meant for bugs in this library, not general advice. You might consider joining the [Pulsar slack community](https://apache-pulsar.herokuapp.com/) if you're looking to discuss your problem more generally.

My guess is you probably want to use a subscription with `SubscriptionInitialPosition.Earliest` and no seeking.

> This adds a constraint that this Record ingester service has to be up before
we put start Record pump service.

That problem is solved using `SubscriptionInitialPosition.Earliest` in your `ConsumerConfig`.

> If my record ingester service goes down (due to an issue or due to maintenance), the messages
produced on pulsar by record pump service will not get consumed after the ingester service is back up.
These messages are lost and never gets consumed.

That should not be true as long as your consumer attaches to the same subscription when the ingestion service comes back up. In your example you're using `Subscription.generate` directly when creating your consumer, which is probably not what you'd want in a production service. Pulsar uses the subscription to keep track of which messages have been consumed, which seems like something that'd be useful in your use case.

**Comment by msg4ashish** [comment]
@gmethvin ,

Thanks for your suggestion. I did try SubscriptionInitialPosition.Earliest without any seeking and that didn't solve the issue. But let me try out taking help on slack community as you suggested.

Thanks again for your time.
